import ThemeSwitcher from "./components/ThemeSwitcher";
import "./globals.css";
import Providers from "./providers";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${inter.className} flex flex-col bg-tremor-background-subtle px-2 py-8 dark:bg-dark-tremor-background-subtle lg:px-20`}
        >
          <ThemeSwitcher />
          {children}
        </body>
      </Providers>
    </html>
  );
}
